### ISSUE TITLE
Coverage testing broken for Python 3.5

### ISSUE THREAD

**Issue by RazerM** [python-astrodynamics/spacetrack#1]
`spacetrack/aio.py   IndexError: pop from empty list`

https://travis-ci.org/python-astrodynamics/spacetrack/jobs/106568823

**Comment by Juanlu001** [comment]
Looks like a bug in coverage https://bitbucket.org/ned/coveragepy/issues/434/indexerror-in-python-35

**Comment by RazerM** [comment]
I installed 4.1b2 which doesn't give an `IndexError`, but it fails when codecov is executing.

https://travis-ci.org/python-astrodynamics/spacetrack/jobs/107308840

**Comment by RazerM** [comment]
Never mind, I forgot that coverage gets installed outside of tox so had to install coverage>=4.1b2 there too.

This can be closed, and I'll change to coverage 4.1 once it's released.
