### ISSUE TITLE
Execution through a proxy firewall

### ISSUE THREAD

**Issue by schmidt-cw** [python-astrodynamics/spacetrack#22]
I often find myself having to execute scripts from behind corporate proxy firewalls. I've not been successful wrapping authentication through a proxy wrapper.

**Comment by RazerM** [comment]
I was considering allowing arguments to be passed to `SpaceTrackClient` that would be passed along to the `requests.Session` instance.

I have `SpaceTrackClient.session` 'public' (i.e. without a leading underscore), but never documented it or said it was part of the public API.

I'll add this to the documentation. You can then do the following (see [Session.proxies](http://docs.python-requests.org/en/master/api/#requests.Session.proxies))

```python
st = SpaceTrackClient(...)
st.session.proxies = {...}
```

**Comment by schmidt-cw** [comment]
Works great on my first test. Thanks!
