### ISSUE TITLE
Option to override base url

### ISSUE THREAD

**Issue by lucas-bremond** [python-astrodynamics/spacetrack#42]
It would be great to add an optional argument to `SpaceTrackClient` to override the base URL, which is currently hardcoded here: https://github.com/python-astrodynamics/spacetrack/blob/master/spacetrack/base.py#L117

The rationale is that SpaceTrack recommends using an alternative server for development and testing, to avoid hitting query limits.

See here: https://www.space-track.org/documentation

> If you are going to develop scripts that query our API and believe that developing/testing them could violate our API guidelines, please Contact Us to request access to our test server. This will enable you to develop your scripts against the same API without affecting the production server.
API Use Guidelines

Something along these lines:

```py
client = SpaceTrackClient(
    identity,
    password,
    base_url='https://testing.space-track.org/'
)
```

What do you think?

**Comment by RazerM** [comment]
I think that's a good idea. Can you submit a PR?

A workaround for now is to subclass the client:

```python
class MyClient(SpaceTrackClient):
    base_url = 'https://testing.space-track.org/'
```

**Comment by RazerM** [comment]
Added by 5bd571091df5648739317d55fee68559d20342b9
