### ISSUE TITLE
Missing module responses

### ISSUE THREAD

**Issue by OrbitalMechanic** [python-astrodynamics/spacetrack#6]
I successfully built spacetrack on a MacBook Pro running Mac OS X ver. 10.11.5 (El Capitan) under Python 2.7 in the Anaconda distribution. The problem I'm having is running the test script test spacetrack.py. I get a message the module responses couldn't be found. Is there a prerequisite I missed?

Please advise.

Sam Dupree.

**Comment by RazerM** [comment]
The test dependencies can be installed using the `test` extra:

```
pip install .[test]
```
(if you're in the same folder as `setup.py`)

I should document this somewhere, maybe both docs and the README.
