### ISSUE TITLE
Allow setting rate limits when initialising

### ISSUE THREAD

**Issue by rob4acre** [python-astrodynamics/spacetrack#73]
I have been using the library to download historical TLEs for some research. Basically, it's just a loop with a call to the tle method
```
    history = st.tle(
                norad_cat_id=norad_cat_id,
                orderby='epoch asc',
                epoch=op.greater_than(launch_date),
                format='tle')
```
I ran the script last night, and I have been getting emails from spacetrack about API violations
```
On 2023-10-20 between 0400 and 500 (UTC), your username sent 301 queries to [www.space-track.org](http://www.space-track.org/), in violation of the API guidelines for this site.
```
I contacted spacetrack admin and the limit is still 300 requests per hour. 

It might be a nice feature to allow users to set their own rate limit below 300 per hour. I only need the data for research, if the script takes longer to run, I don't mind. 

Perhaps when initialising, a user could specify the rate limits they want to use, like
```
st = SpaceTrackClient(identity=identity, password=password, ratelimits=(20, 200))
```

Many thanks for developing this library.

**Comment by RazerM** [comment]
Does this look like something you could use? https://github.com/python-astrodynamics/spacetrack/pull/77
